<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GibeCommerce.Repositories.NPoco" Version="18.0.0.12398" />
    <PackageReference Include="NUnit" Version="4.5.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.1.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gibe.ABTest\Gibe.AbTest.csproj" />
  </ItemGroup>

	<ItemGroup>
		<Content Include="appsettings.test.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>true</CopyToPublishDirectory>
		</Content>
	</ItemGroup>

</Project>
